routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get("/testS", 'TestController@testSimulation');
Route::get("/testExcel","TestController@testExcel");
Route::get('/', function () {
    return redirect('login');
});

Auth::routes();
Route::group(['middleware' => ['auth:web']], function () {
    Route::get('/sync/tech-routing', 'TechRoutingController@syncTechRouting')->name('syncTechRouting');
    Route::get('/work-center-data', 'WorkCenterController@getCenterData')->name('getCenterData');
    Route::resource('resource', 'ResourceSetController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/rest-time/{id}', 'RestTimeController@createData');
    Route::resource('work-type', 'WorkTypeController')->except('show');
    Route::resource('rest-time', 'RestTimeController')->except('show');
    Route::get('/search-bom', 'BomController@index')->name('search-bom');
    Route::get('/result-bom', 'BomController@resultBom')->name('result-bom');
    Route::get('/list-bom/{data}', 'BomController@listBom')->name('list-bom');
    Route::get('/sale-order', 'SaleOrderController@index')->name('sale-order');
    Route::get('/work-center', 'WorkCenterController@index')->name('work-center');
    // Route::get('/work-center-data', 'WorkCenterController@getCenterData')->name('getCenterData');
    Route::get('/load-schedule', 'LoadScheduleController@index')->name('load-schedule');
    Route::get('/full-calendar', 'CalendarController@fullcalendar')->name('full-calendar');
    Route::get('/year-calendar', 'CalendarController@yearcalendar')->name('year-calendar');
    Route::post('/compare-data', 'LoadScheduleController@importFile')->name('compare-data');
    Route::get('/work-center/{id}/show', 'WorkCenterController@show')->name('work-center-show');
    Route::get('/sale-order-result', 'SaleOrderController@orderResult')->name('sale-order-result');
    Route::put('/rest-time/{id}/setup/{setup_id}', 'RestTimeController@updateData')->name('update-data');
    Route::get('/process-calendar', 'ProcessCalendarController@processcalendar')->name('process-calendar');
    Route::delete('/rest-time/{id}/setup/{setup_id}', 'RestTimeController@deleteData')->name('delete-data');
    Route::get('/load-schedule-result', 'LoadScheduleController@scheduleResult')->name('load-schedule-result');
    Route::get('/sale-order-result-form', 'SaleOrderController@synchroizedForm')->name('sale-order-result-form');
    Route::get('/load-manufacture-result','LoadScheduleController@manufacture')->name('load-manufacture-result');
    Route::get('/adjust-process-calendar', 'ProcessCalendarController@showProcessCalendar')->name('show-process-calendar');

    Route::resource('management', 'ManageMentController');
    Route::resource('role-set', 'RoleSetController');

    Route::group(['prefix' => 'tech-routing'], function () {
// Route::get('/sync/tech-routing', 'TechRoutingController@syncTechRouting')->name('syncTechRouting');
        Route::get('/', 'TechRoutingController@index')->name('tech-routing.index');
        Route::get('/edit/{id}', 'TechRoutingController@edit');
        Route::put('/{id}', 'TechRoutingController@update')->name('tech-routing.update');
    });

    Route::group(['prefix' => 'simulation'], function () {
        Route::get('source-order', 'SimulationSchemeController@sourceOrder')->name('source-order');
        Route::get('get-source-order', 'SimulationSchemeController@getSourceOrderData')->name('get-source-order');
        Route::get('source-order-result', 'SimulationSchemeController@sourceOrderResult')->name('source-order-result');
        Route::get('get-manufacture-order', 'SimulationSchemeController@getManufactureOrderData')->name('get-manufacture-order');
        Route::get('manufacture-order-result', 'SimulationSchemeController@manufactureOrderResult')->name('manufacture-order-result'); //return manumacture.blade need data
        Route::get('load-source-order', 'SimulationSchemeController@getLoadSourceOrder')->name('load-source-order');
        Route::get('get-generate-scheme', 'SimulationSchemeController@getGenerateSimulation')->name('get-generate-scheme');
        Route::post('generate-simulation-scheme', 'SimulationSchemeController@generateSimulation')->name('generate-simulation-scheme');
        Route::get('search-scheme', 'SimulationSchemeController@searchScheme')->name('search-scheme');
        Route::get('search-scheme/{id}/result', 'SimulationSchemeController@searchSchemeResult');
        Route::get('search-scheme-result', 'SimulationSchemeController@getSearchSchemeResult');
        Route::post('get-search-scheme', 'SimulationSchemeController@getSearchScheme');
        Route::get('confirm-scheme','SimulationSchemeController@confirmSimulation')->name('confirm-scheme-result') ;
    });

    Route::get('/workcenter/add-default-resource', 'WorkCenterController@addDefaultResource')->name('resource-sync');

    //塗裝吊勾
    Route::resource('coating','CoatingSetController');
    Route::get('/sync','CoatingSetController@SyncToRemote')->name('sync');

    //異常原因設定
    Route::get('/abnormal-set', 'AbnormalSetController@index')->name('abnormal-set');
    Route::get('/abnormal-ctrl-add', 'AbnormalSetController@controll_page')->name('abnormal-ctrl-add');
    Route::get('/abnormal-add', 'AbnormalSetController@add')->name('abnormal-add');
    Route::get("/abnormal-del/{id}", 'AbnormalSetController@delete');
    Route::get("/abnormal-ctrl-fix/{id}", 'AbnormalSetController@controll_page');
    Route::get("/abnormal-fix/{id}", 'AbnormalSetController@edit');
});

resources/views/system/createsourceset.blade.php
@extends('layouts.myapp')

@section('css')
<style>
    .space-item {
        margin-left: 10px;
    }
    .panel-default {
        border-color: #000000;
    }
    .panel-default > .panel-heading {
        color: #fff;
        background-color: #000000;
        border-color: #000000;
    }
    .form-horizontal .control-label {
        text-align: center;
    }
    hr {
        border-top: 1px solid #ccc;
    }
    .btn-secondary {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }
    .btn-secondary:hover {
        color: #fff;
        background-color: #5a6268;
        border-color: #545b62;
    }
    .btn.focus, .btn:focus, .btn:hover {
        color: #fff;
    }
</style>
@endsection

@section('content')
<div id="page-wrapper">
    <div class="container-fluid">
        <h2>資源設定</h2>
        <ol class="breadcrumb">
            <img src="{{ asset('img/u12.png') }}">
            <span class="space-item">系統管理</span>
            <span class="space-item">></span>
            <span class="space-item">資源設定<span>
            <span class="space-item">></span>
            <span class="space-item">編輯資源設定</span>
        </ol>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">資料編輯</div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="{{ route('resource.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label class="col-md-2 control-label">資源代碼</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="resource_id" required>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">資源名稱</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="resource_name" required>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">資源類別</label>
                                <div class="col-md-10">
                                    <select id="resource_type" name="resource_type" class="form-control" required>
                                        <option disabled selected value="">--- 請選擇資源類別 ---</option>
                                        <option value="設備" >設備</option>
                                        <option value="人力" >人力</option>
                                    </select>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">設備編碼</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="device_id" required>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">機台名稱/規格</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="device_name" required>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">機台數量</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="device_qty" required>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">製程類別</label>
                                <div class="col-md-10">
                                    <select id="routing_select" name="routing_select" class="form-control" onchange="getCenter()" required>
                                        <option disabled selected value="">--- 請選擇班別類型 ---</option>
                                        <option value="11" >鐳射</option>
                                        <option value="12" >NCT</option>
                                        <option value="13" >P2</option>
                                        <option value="20" >沖床</option>
                                        <option value="30" >點焊</option>
                                        <option value="40" >塗裝</option>
                                        <option value="50" >裝配</option>
                                        <option value=""   >其它</option>
                                    </select>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">工作中心代碼</label>
                                <div class="col-md-10">
                                    <select class="form-control" id="workcenter_sel" name="workcenter_id" required>
                                    </select>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">預設班別</label>
                                <div class="col-md-10">
                                    <select class="form-control" id="assign_work" name="assign_work" required>
                                    </select>                        
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">標準前置(小時)</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="standard_pre_time">
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">標準TCT(秒)</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="standard_time">
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">標準TCT</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="standard_tct">
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">標準換線(分)</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="change_time">
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">設備人力倍數</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="device_multiple">
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">是否為預設資源中心</label>
                                <div class="col-md-10">
                                    <select id="is_default" name="is_default" class="form-control" required>
                                        <option value="0" >否</option>
                                        <option value="1" >是</option>
                                    </select>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group" id="painting">
                            </div>
                            <hr>
                            <div style="text-align:center">
                                <button type="submit" id="sendBtn" class="btn btn-success btn-lg" style="width:45%">確認</button>
                                <a class="btn btn-secondary btn-lg" href="{{ route('resource.index') }}" style="width:45%">返回</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>


    if ('{{ session('message') }}') {
        alert('{{ session('message') }}');
    }
    const getShift = () => {
        axios.get('{{route('get-work-time')}}')
        .then(({data}) => {
            console.log(data);
            $("#assign_work").append(`<option disabled selected value="">--- 請選擇 ---</option>`)
            data.forEach(data => {
                $("#assign_work").append(`<option value="${data.id}">${data.name}</option>`)
            })
        });
    }
    const getCenter = () => {
        axios.get('{{ route('getcenter') }}', {
            params: {
                value: $('#routing_select').val(),
            }
        })
        .then(({ data }) => {
            $("#workcenter_sel").empty();
            $("#workcenter_sel").append(`
                <option disabled selected value="">--- 請選擇 ---</option>
            `)
            data.forEach(data => {
                $("#workcenter_sel").append(`
                    <option value="${data.workcenter_id}">${data.workcenter_id}</option>
                `);
            })
        });
        if($('#routing_select').val()==40) {
            $('#painting').append(`
                <label class="col-md-2 control-label">烤漆線總長(公尺)</label>
                <div class="col-md-10" style="margin-bottom: 15px;">
                    <input type="text" class="form-control" name="paint_length" required ">
                </div>
                <label class="col-md-2 control-label">總鉤數</label>
                <div class="col-md-10" style="margin-bottom: 15px;">
                    <input type="text" class="form-control" name="hook_qty" required ">
                </div>
                <label class="col-md-2 control-label">換色時間(分)</label>
                <div class="col-md-10" style="margin-bottom: 15px;">
                    <input type="text" class="form-control" name="change_color_time" required ">
                </div>
                <label class="col-md-2 control-label">標準換模時間(分)</label>
                <div class="col-md-10" style="margin-bottom: 15px;">
                    <input type="text" class="form-control" name="standard_change_time" required ">
                </div>
                <label class="col-md-2 control-label">標準速率(D/T)M/min</label>
                <div class="col-md-10" style="margin-bottom: 15px;">
                    <input type="text" class="form-control" name="standard_rate" required >
                </div>
                <label class="col-md-2 control-label">完工空勾距離</label>
                <div class="col-md-10">
                    <input type="text" class="form-control" name="empty_hook_distance" required >
                </div>
            `);
        }
        else {
            $('#painting').empty();
        }
    }
    getShift();

</script>

@endsection

resources/views/system/editresttime.blade.php
@extends('layouts.myapp')

@section('css')
<style>
    .space-item {
        margin-left: 10px;
    }
    .panel-default {
        border-color: #000000;
    }
    .panel-default > .panel-heading {
        color: #fff;
        background-color: #000000;
        border-color: #000000;
    }
    .form-horizontal .control-label {
        text-align: center;
    }
    hr {
        border-top: 1px solid #ccc;
    }
    .btn-secondary {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }
    .btn-secondary:hover {
        color: #fff;
        background-color: #5a6268;
        border-color: #545b62;
    }
    .btn.focus, .btn:focus, .btn:hover {
        color: #fff;
    }
</style>
@endsection

@section('content')
<div id="page-wrapper">
    <div class="container-fluid">
        <h2>休息時間設定</h2>
        <ol class="breadcrumb">
            <img src="{{ asset('img/u12.png') }}">
            <span class="space-item">系統管理</span>
            <span class="space-item">></span>
            <span class="space-item">休息時間設定<span>
            <span class="space-item">></span>
            <span class="space-item">新增休息時間</span>
        </ol>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">編輯休息類別</div>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            <form action="{{ route('rest-time.update', $result->id) }}" method="POST">
                                @csrf
                                @method('PUT')
                            <div class="form-group">
                                <label class="col-md-2 control-label">休息名稱</label>
                                <div class="col-md-10">
                                    <input class="form-control" name="rest_name" value="{{ $result->rest_name }}" required>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">休息類型</label>
                                <div class="col-md-10">
                                    <select name="work_type" class="form-control" required>
                                        <option disabled selected value="">--- 請選擇班別類型 ---</option>
                                        <option value="正常班" {{ $result->work_type === '正常班' ? 'selected' : '' }}>正常班</option>
                                        <option value="早班" {{ $result->work_type === '早班' ? 'selected' : '' }}>早班</option>
                                        <option value="中班" {{ $result->work_type === '中班' ? 'selected' : '' }}>中班</option>
                                        <option value="晚班" {{ $result->work_type === '晚班' ? 'selected' : '' }}>晚班</option>
                                        <option value="大夜班" {{ $result->work_type === '大夜班' ? 'selected' : '' }}>大夜班</option>
                                        <option value="混合型" {{ $result->work_type === '混合型' ? 'selected' : '' }}>混合型</option>
                                    </select>
                                </div>
                            </div>

                                <div style="text-align:center">
                                    <button type="submit" id="sendBtn" class="btn btn-primary">更新</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">編輯休息時間</div>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            <div id="restRow">
                                @foreach ($result->restSetup as $key => $data)
                                    <div id="restId">
                                        <hr>
                                        <div class="form-group">
                                            <form action="{{ route('update-data', [$result->id, $data->id]) }}" method="POST">
                                                @csrf
                                                @method('PUT')
                                                <label class="col-md-2 control-label">第{{ ++$key }}段休息</label>
                                                <div class="col-md-5">
                                                    <input id="restRemark" name="remark" class="form-control" value="{{ $data->remark }}" required>
                                                </div>
                                                <div class="col-md-4">
                                                    <select name="type" class="form-control" required>
                                                        <option disabled selected value="">--- 請選擇類型 ---</option>
                                                        <option value="休息" {{ $data->type === '休息' ? 'selected' : '' }}>休息</option>
                                                        <option value="用餐" {{ $data->type === '用餐' ? 'selected' : '' }}>用餐</option>
                                                    </select>
                                                </div>
                                                <div class="col-md-1">
                                                    <button onclick="" class="btn btn-primary">更新</button>
                                                </div>
                                                <br>
                                                <br>
                                                <label class="col-md-2 control-label"></label>
                                                <div class="col-md-4">
                                                    <input name="start" type="time" class="form-control" value="{{ $data->start }}" required>
                                                </div>
                                                <div class="col-md-1" style="text-align:center;">
                                                    <label style="margin:7px;"> ~ </label>
                                                </div>
                                                <div class="col-md-4">
                                                    <input name="end" type="time" class="form-control" value="{{ $data->end }}" required>
                                                </div>
                                            </form>
                                            <form action="{{ route('delete-data', [$result->id, $data->id]) }}" method="POST">
                                                @method('DELETE')
                                                @csrf
                                                <div class="col-md-1">
                                                    <button class="btn btn-danger">刪除</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                            <hr>
                            <div style="text-align:center">
                                <button onclick="addRestRow()" class="btn btn-success" type="button">+</button>
                                <button onclick="minusRestRow()" class="btn btn-secondary" style="width:36px" type="button">-</button>
                            </div>
                            <hr>
                            <div style="text-align:center">
                                <a class="btn btn-success btn-lg" href="{{ route('rest-time.index') }}" style="width:45%">返回</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    if ('{{ session('message') }}') {
        alert('{{ session('message') }}');
    }
    const restData = '{{!! $result->restSetup !!}}';
    const restGroupData = '{{!! $result->id !!}}'
    const restGroupId = ~~restGroupData.match(/\d+/)[0];
    let qty = JSON.parse('{"restData":' + restData.slice(1)).restData.length;
    let restId = qty;
    const addRestRow = () => {
        $('#restRow').append(`
            <div id="restId${++restId}">
                <hr>
                <div class="form-group">
                    <form action="/rest-time/${restGroupId}" method="POST">
                        @csrf
                        <label class="col-md-2 control-label">第${restId}段休息</label>
                        <div class="col-md-5">
                            <input id="restRemark${restId}" name="remark" class="form-control" required>
                        </div>
                        <div class="col-md-4">
                            <select name="type" class="form-control" required>
                                <option disabled selected value="">--- 請選擇類型 ---</option>
                                <option value="休息">休息</option>
                                <option value="用餐">用餐</option>
                            </select>
                        </div>
                        <div class="col-md-1">
                            <button class="btn btn-success">新增</button>
                        </div>
                        <br>
                        <br>
                        <label class="col-md-2 control-label"></label>
                        <div class="col-md-4">
                            <input name="start" type="time" class="form-control" required>
                        </div>
                        <div class="col-md-1" style="text-align:center;">
                            <label style="margin:7px;"> ~ </label>
                        </div>
                        <div class="col-md-4">
                            <input name="end" type="time" class="form-control" required>
                        </div>
                    </form>
                </div>
            </div>
        `);
    }
    const minusRestRow = () => {
        $(`#restId${restId}`).remove();
        (restId == qty) ? restId = qty : restId--;
    }
</script>
@endsection

resources/views/system/workrouting.blade.php
@extends('layouts.myapp')

@section('css')
<style>
    .space-item {
        margin-left: 10px;
    }
    .breadcrumb-custom {
        background-color: #3D404C;
        width: 99%;
        margin:0px auto;
        padding: 15px 15px;
        margin-bottom: 20px;
        list-style: none;
        border-radius: 4px;
        color: #fff;
    }
    .total-data {
        width: 98%;
        margin:0px auto;
        /* padding: 0px 10px; */
    }
    .table-pos {
        margin: 0px auto;
        width: 98%;
    }
    .thead-color {
        background-color: #E85726;
        color: #fff;
        height: 10px;
    }
</style>
@endsection

@section('content')
<div id="page-wrapper">
    <div class="container-fluid">
        <h2>工藝路線設定</h2>
        <ol class="breadcrumb">
            <img src="{{ asset('img/u12.png') }}">
            <span class="space-item">系統管理</span>
            <span class="space-item">></span>
            <span class="space-item">工藝路線設定<span>
        </ol>
        <div class="breadcrumb-custom">
            <span>資料列表</span>
            <div style="float:right; margin-top:-7px">
                <button class="btn btn-success">新增</button>
            </div> 
        </div>
        <div class="total-data">載入筆數 | 共 5 筆</div>
        <div style="margin-top:15px;">
            <table class="table table-striped table-pos">
                <thead class="thead-color">
                    <tr>
                        <th scope="col">序</th>
                        <th scope="col">工藝路線</th>
                        <th scope="col">預設班別</th>
                        <th scope="col">標準TCT(秒)</th>
                        <th scope="col">預設資源中心</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>一群-雷射</td>
                        <td>正常班_標準</td>
                        <td>60</td>
                        <td>一群雷射機</td>
                        <td>
                            <button class="btn btn-primary">編輯</button>
                            &nbsp
                            <button class="btn btn-danger">刪除</button>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>一群-P2</td>
                        <td>正常班_標準</td>
                        <td>60</td>
                        <td>一群CNC轉塔沖孔機</td>
                        <td>
                            <button class="btn btn-primary">編輯</button>
                            &nbsp
                            <button class="btn btn-danger">刪除</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection