routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get("/testS", 'TestController@testSimulation');
Route::get("/testExcel","TestController@testExcel");
Route::get('/', function () {
    return redirect('login');
});

Auth::routes();
Route::group(['middleware' => ['auth:web']], function () {
    Route::get('/sync/tech-routing', 'TechRoutingController@syncTechRouting')->name('syncTechRouting');
    Route::get('/work-center-data', 'WorkCenterController@getCenterData')->name('getCenterData');
    Route::resource('resource', 'ResourceSetController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/rest-time/{id}', 'RestTimeController@createData');
    Route::resource('work-type', 'WorkTypeController')->except('show');
    Route::resource('rest-time', 'RestTimeController')->except('show');
    Route::get('/search-bom', 'BomController@index')->name('search-bom');
    Route::get('/result-bom', 'BomController@resultBom')->name('result-bom');
    Route::get('/list-bom/{data}', 'BomController@listBom')->name('list-bom');
    Route::get('/sale-order', 'SaleOrderController@index')->name('sale-order');
    Route::get('/work-center', 'WorkCenterController@index')->name('work-center');
    // Route::get('/work-center-data', 'WorkCenterController@getCenterData')->name('getCenterData');
    Route::get('/load-schedule', 'LoadScheduleController@index')->name('load-schedule');
    Route::get('/full-calendar', 'CalendarController@fullcalendar')->name('full-calendar');
    Route::get('/year-calendar', 'CalendarController@yearcalendar')->name('year-calendar');
    Route::post('/compare-data', 'LoadScheduleController@importFile')->name('compare-data');
    Route::get('/work-center/{id}/show', 'WorkCenterController@show')->name('work-center-show');
    Route::get('/sale-order-result', 'SaleOrderController@orderResult')->name('sale-order-result');
    Route::put('/rest-time/{id}/setup/{setup_id}', 'RestTimeController@updateData')->name('update-data');
    Route::get('/process-calendar', 'ProcessCalendarController@processcalendar')->name('process-calendar');
    Route::delete('/rest-time/{id}/setup/{setup_id}', 'RestTimeController@deleteData')->name('delete-data');
    Route::get('/load-schedule-result', 'LoadScheduleController@scheduleResult')->name('load-schedule-result');
    Route::get('/sale-order-result-form', 'SaleOrderController@synchroizedForm')->name('sale-order-result-form');
    Route::get('/load-manufacture-result','LoadScheduleController@manufacture')->name('load-manufacture-result');
    Route::get('/adjust-process-calendar', 'ProcessCalendarController@showProcessCalendar')->name('show-process-calendar');

    Route::resource('management', 'ManageMentController');
    Route::resource('role-set', 'RoleSetController');

    Route::group(['prefix' => 'tech-routing'], function () {
// Route::get('/sync/tech-routing', 'TechRoutingController@syncTechRouting')->name('syncTechRouting');
        Route::get('/', 'TechRoutingController@index')->name('tech-routing.index');
        Route::get('/edit/{id}', 'TechRoutingController@edit');
        Route::put('/{id}', 'TechRoutingController@update')->name('tech-routing.update');
    });

    Route::group(['prefix' => 'simulation'], function () {
        Route::get('source-order', 'SimulationSchemeController@sourceOrder')->name('source-order');
        Route::get('get-source-order', 'SimulationSchemeController@getSourceOrderData')->name('get-source-order');
        Route::get('source-order-result', 'SimulationSchemeController@sourceOrderResult')->name('source-order-result');
        Route::get('get-manufacture-order', 'SimulationSchemeController@getManufactureOrderData')->name('get-manufacture-order');
        Route::get('manufacture-order-result', 'SimulationSchemeController@manufactureOrderResult')->name('manufacture-order-result'); //return manumacture.blade need data
        Route::get('load-source-order', 'SimulationSchemeController@getLoadSourceOrder')->name('load-source-order');
        Route::get('get-generate-scheme', 'SimulationSchemeController@getGenerateSimulation')->name('get-generate-scheme');
        Route::post('generate-simulation-scheme', 'SimulationSchemeController@generateSimulation')->name('generate-simulation-scheme');
        Route::get('search-scheme', 'SimulationSchemeController@searchScheme')->name('search-scheme');
        Route::get('search-scheme/{id}/result', 'SimulationSchemeController@searchSchemeResult');
        Route::get('search-scheme-result', 'SimulationSchemeController@getSearchSchemeResult');
        Route::post('get-search-scheme', 'SimulationSchemeController@getSearchScheme');
        Route::get('confirm-scheme','SimulationSchemeController@confirmSimulation')->name('confirm-scheme-result') ;
    });

    Route::get('/workcenter/add-default-resource', 'WorkCenterController@addDefaultResource')->name('resource-sync');

    //塗裝吊勾
    Route::resource('coating','CoatingSetController');
    Route::get('/sync','CoatingSetController@SyncToRemote')->name('sync');

    //異常原因設定
    Route::get('/abnormal-set', 'AbnormalSetController@index')->name('abnormal-set');
    Route::get('/abnormal-ctrl-add', 'AbnormalSetController@controll_page')->name('abnormal-ctrl-add');
    Route::get('/abnormal-add', 'AbnormalSetController@add')->name('abnormal-add');
    Route::get("/abnormal-del/{id}", 'AbnormalSetController@delete');
    Route::get("/abnormal-ctrl-fix/{id}", 'AbnormalSetController@controll_page');
    Route::get("/abnormal-fix/{id}", 'AbnormalSetController@edit');
});

app/Http/Controllers/ManageMentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\ManageMentRepository;
use App\Services\AssignTypeService;

class ManageMentController extends Controller
{
    protected $manageRepo;
    protected $assingService;

    public function __construct(ManageMentRepository $manageRepo, AssignTypeService $assingService)
    {
        $this->manageRepo = $manageRepo;
        $this->assingService = $assingService;
    }

    public function index()
    {
        return view('management.index');
    }

    public function edit($id)
    {
        $data = $this->manageRepo->find($id);

        return view('management.edit', ['data' => $data]);
    }

    public function create()
    {
        return view('management.create');
    }

    public function store()
    {
        $data = $this->manageRepo->create(request()->only('account', 'name', 'role_id'));

        if ($data) {
            return redirect()->route('management.index');
        }
    }

    public function update($id)
    {
        $this->manageRepo->update($id, request(['account', 'name', 'role_id']));

        return redirect()->route('management.index');
    }

    public function destroy($id)
    {
        $this->manageRepo->destroy($id);

        return redirect()->route('management.index');
    }

    public function managementIndex()
    {
        $data = $this->manageRepo->managementIndex(request()->amount);

        return $data;
    }

    public function getRole()
    {
        return $this->assingService->role();
    }

    public function getOrganization()
    {
        return $this->assingService->organization();
    }
}

resources/views/management/create.blade.php
@extends('layouts.myapp')

@section('css')
<style>
    .space-item {
        margin-left: 10px;
    }
    .panel-default {
        border-color: #000000;
    }
    .panel-default > .panel-heading {
        color: #fff;
        background-color: #000000;
        border-color: #000000;
    }
    .form-horizontal .control-label {
        text-align: center;
    }
    hr {
        border-top: 1px solid #ccc;
    }
    .btn-secondary {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }
    .btn-secondary:hover {
        color: #fff;
        background-color: #5a6268;
        border-color: #545b62;
    }
    .btn.focus, .btn:focus, .btn:hover {
        color: #fff;
    }
</style>
@endsection

@section('content')
<div id="page-wrapper">
    <div class="container-fluid">
        <h2>人員帳號管理</h2>
        <ol class="breadcrumb">
            <img src="{{ asset('img/u12.png') }}">
            <span class="space-item">系統管理</span>
            <span class="space-item">></span>
            <span class="space-item">人員帳號管理<span>
            <span class="space-item">></span>
            <span class="space-item">編輯帳號資訊</span>
        </ol>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">資料編輯</div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="{{ route('management.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label class="col-md-2 control-label">人員編號</label>
                                <div class="col-md-10">
                                <input type="text" class="form-control" name="account" required value="">
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">人員名稱</label>
                                <div class="col-md-10">
                                <input type="text" class="form-control" name="name" required value="">
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">所屬組織</label>
                                <div class="col-md-10">
                                    <select class="form-control" id="organization_sel" name="factory_id" required value="">
                                    </select>
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">歸屬角色</label>
                                <div class="col-md-10">
                                    <select class="form-control" id="role_sel" name="role_id" required value="">
                                    </select>
                                </div>
                            </div>
                            <hr>
                            <div style="text-align:center">
                                <input type="submit" id="sendBtn" class="btn btn-success btn-lg" style="width:45%" value="確認">
                                <a class="btn btn-secondary btn-lg" href="{{ route('management.index') }}" style="width:45%">返回</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    const getRole = () => {
            axios.get('{{ route('getRole') }}', {})
        .then(({ data }) => {
            $('#role_sel').empty();
            data.forEach(data => {
                    $('#role_sel').append(`
                        <option value="${data.id}">${data.name}</option>
                    `);
                })
        });
    }
    const getOrganization = () => {
            axios.get('{{ route('getOrganization') }}', {})
        .then(({ data }) => {
            $('#organization_sel').empty();
            data.forEach(data => {
                    $("#organization_sel").append(`
                        <option value="${data.factory_id}">${data.name}</option>
                    `);
                })
        });
    }
    getRole();
    getOrganization();
</script>

@endsection

resources/views/management/edit.blade.php
@extends('layouts.myapp')

@section('css')
<style>
    .space-item {
        margin-left: 10px;
    }
    .panel-default {
        border-color: #000000;
    }
    .panel-default > .panel-heading {
        color: #fff;
        background-color: #000000;
        border-color: #000000;
    }
    .form-horizontal .control-label {
        text-align: center;
    }
    hr {
        border-top: 1px solid #ccc;
    }
    .btn-secondary {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }
    .btn-secondary:hover {
        color: #fff;
        background-color: #5a6268;
        border-color: #545b62;
    }
    .btn.focus, .btn:focus, .btn:hover {
        color: #fff;
    }
</style>
@endsection

@section('content')
<div id="page-wrapper">
    <div class="container-fluid">
        <h2>人員帳號管理</h2>
        <ol class="breadcrumb">
            <img src="{{ asset('img/u12.png') }}">
            <span class="space-item">系統管理</span>
            <span class="space-item">></span>
            <span class="space-item">人員帳號管理<span>
            <span class="space-item">></span>
            <span class="space-item">編輯帳號資訊</span>
        </ol>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">資料編輯</div>
                    <div class="panel-body">
                        <form class="form-horizontal" action="{{ route('management.update', $data->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label class="col-md-2 control-label">人員編號</label>
                                <div class="col-md-10">
                                <input type="text" class="form-control" name="account" required value="{{ $data->account }}">
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">人員名稱</label>
                                <div class="col-md-10">
                                <input type="text" class="form-control" name="name" required value="{{ $data->name }}">
                                </div>
                            </div>
                            <hr>
                            <div class="form-group">
                                <label class="col-md-2 control-label">歸屬角色</label>
                                <div class="col-md-10">
                                    <select class="form-control" id="role_sel" name="role_id" required value="{{ $data->role_id }}">
                                    </select>
                                </div>
                            </div>
                            <hr>
                            <div style="text-align:center">
                                <input type="submit" id="sendBtn" class="btn btn-success btn-lg" style="width:45%" value="確認">
                                <a class="btn btn-secondary btn-lg" href="{{ route('management.index') }}" style="width:45%">返回</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    const getRole = () => {
            axios.get('{{ route('getRole') }}', {})
        .then(({ data }) => {
            $('#role_sel').empty();
            data.forEach(data => {
                if ( {{ $data->role_id }} === data.id ) {
                    $("#role_sel").append(`
                        <option disabled selected value=" ${data.id}">${data.name}</option>
                    `)
                }
                else {
                    $('#role_sel').append(`
                        <option value="${data.id}">${data.name}</option>
                    `);
                }
            })
        });
    }
    getRole();
</script>

@endsection

resources/views/management/index.blade.php
@extends('layouts.myapp')

@section('css')
<style>
    .space-item {
        margin-left: 10px;
    }
    .breadcrumb-custom {
        background-color: #3D404C;
        width: 99%;
        margin:0px auto;
        padding: 15px 15px;
        margin-bottom: 20px;
        list-style: none;
        border-radius: 4px;
        color: #fff;
    }
    .total-data {
        width: 98%;
        margin:0px auto;
    }
    .table-pos {
        margin: 0px auto;
        width: 98%;
    }
    .thead-color {
        background-color: #E85726;
        color: #fff;
        height: 10px;
    }
</style>
@endsection

@section('content')
<div id="page-wrapper">
    <div class="container-fluid">
        <h2>人員帳號管理</h2>
        <ol class="breadcrumb">
            <img src="{{ asset('img/u12.png') }}">
            <span class="space-item">系統管理</span>
            <span class="space-item">></span>
            <span class="space-item">人員帳號管理<span>
        </ol>
        <div class="breadcrumb-custom">
            <span>資料列表</span>
            <div style="float:right; margin-top:-7px">
                <a href="{{ route('management.create') }}" class="btn btn-success">新增</a>
            </div>
        </div>
        <div class="total-data">
            載入筆數 |
            <span id="data-num"></span>
        </div>
        <div style="margin-top:15px;">
            <table class="table table-striped table-pos" id="management-table">
                <thead class="thead-color">
                    <tr>
                        <th scope="col">序</th>
                        <th scope="col">人員編號</th>
                        <th scope="col">人員名稱</th>
                        <th scope="col">角色</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <div style="text-align:right">
                <span style="display: inline-block; margin-top: 27px;">
                        <span>每頁顯示筆數</span>
                        <select id="amount" onchange="getManagementIndex();$('#pagination-demo').twbsPagination('destroy');">
                            <option value="10" selected>10</option>
                            <option value="25">25</option>
                            <option value="50">50</option>
                        </select>
                </span>
                <ul id="pagination-demo" class="pagination-sm" style="vertical-align: top;"></ul>
            </div>
        </div>
    </div>
</div>

<script>
    function checkyn(){
        var check = confirm("是否要刪除該筆資料");
        if (check) {
            return true;
        } else {
            return false;
        }
    }
    let lastPage;
    const getManagementIndex = (page = 1) => {
        const amount = $('#amount').val();
        axios.get('{{ route('managementIndex') }}',{
            params: {
                amount,
                page,
            }
        }).then(({ data }) => {
            lastPage = data.last_page;

            const orders = data.data;

            $('#data-num').text(`共 ${data.total} 筆`);
            $('#management-table tbody').empty();
            orders.forEach((order, key) => {
                $('#management-table tbody').append(`
                    <tr>
                        <th scope="row">${key + 1 + (page - 1) * amount}</th>
                        <td>${order.account}</td>
                        <td>${order.name}</td>
                        <td>${order.role.name}</td>
                        <td>
                            <a href="management/${order.id}/edit" class="btn btn-primary">編輯</a>
                            <form action="management/${order.id}" onsubmit="return checkyn()" method="POST" style="display:inline-block">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger">刪除</button>
                            </form>
                        </td>
                    </tr>
                `)
            });
            $('#pagination-demo').twbsPagination({
                totalPages: lastPage,
                visiblePages: 5,
                first:'頁首',
                last:'頁尾',
                prev:'<',
                next:'>',
                initiateStartPageClick: false,
                onPageClick: function (event, page) {
                    getManagementIndex(page)
                }
            });
        });
    }
    getManagementIndex();
</script>

@endsection